name: Sync-fork
on:
  schedule:
    - cron: '0 11 * * *'
permissions:
  contents: write
  actions: write
  workflows: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/newton-physics/newton.git
    
    - name: Fetch and rebase main
      run: |
        git fetch upstream
        git fetch origin
        git checkout main
        git rebase upstream/main
        git push origin main --force-with-lease
    
    - name: Rebase dev
      run: |
        git checkout dev
        git rebase main
        git push origin dev --force-with-lease
